"""
This module gives an executable interface for viewing aggregation reports. This
should be launched `python -m pious aggregation_viewer`
"""

from pathlib import Path
from typing import Optional
from ..pio.pio_aggregation_report import PioAggregationReport
from code import InteractiveConsole
from matplotlib import pyplot as plt
from ansi.color import fg, fx
import typer
from typing_extensions import Annotated
from rich.console import Console
from rich.panel import Panel
import sys

banner = f"""
Launching interactive aggregation report session. Variable `ar` stores the
aggregation report. Use

+ `{fx.bold}{fg.blue}ar.filter("..."){fx.reset}` to filter the report.
+ `{fx.bold}{fg.blue}ar.reset(){fx.reset}` to reset all filters
+ `{fx.bold}{fg.blue}ar.plot(){fx.reset}` to plot the report

"""


def aggregation_viewer_cmd(
    report_dir: Annotated[
        Optional[Path],
        typer.Argument(
            help="Path to directory with report.csv (generated by Pio). Defaults to current directory.",
        ),
    ] = None,
    cfr_database: Annotated[
        Optional[Path],
        typer.Argument(
            help="Path to CFR Database (cfr files that report was generated from) (optional).",
        ),
    ] = None,
    interactive: Annotated[
        bool, typer.Option("--interactive", "-I", help="Launch interactive console")
    ] = False,
    filter_expr: Annotated[
        str, typer.Option("--filter", "-F", help="Filter aggregation report")
    ] = "",
    plot: Annotated[bool, typer.Option(help="Plot aggregation report results")] = False,
):
    if report_dir is None:
        report_dir = "."
    try:
        ar = PioAggregationReport(report_dir, cfr_database)
    except RuntimeError as e:
        print(f"Couldn't load aggregation report for reports directory '{report_dir}'")
        return

    if filter_expr:
        try:
            ar.filter(filter_expr)
        except RuntimeError as e:
            console = Console()
            console.print(
                Panel(
                    f"Error applying filter expression {filter_expr} to aggregation report\n{e}",
                    title="Filter Error",
                    title_align="left",
                    style="bold red",
                )
            )
            sys.exit(1)

    if plot:

        plt.ioff()
        ar.plot()
        plt.ion()
    if interactive:
        InteractiveConsole(locals={"ar": ar}).interact(banner=banner)
    else:
        ar.paginate()
